// Caoren Cup web visual modification modules
// Generated by phase2_fix_full_caoren_module_params.js
// Keep command grammar aligned with game-plugin/Features/*Feature.cs.

export type CaorenModParamType = 'select' | 'number' | 'text' | 'boolean';

export type CaorenModOption = { label: string; value: string | number | boolean };

export type CaorenModParam = {
  key: string;
  name?: string;
  label: string;
  type: CaorenModParamType;
  defaultValue?: string | number | boolean;
  default?: string | number | boolean;
  placeholder?: string;
  helperText?: string;
  description?: string;
  min?: number;
  max?: number;
  step?: number;
  required?: boolean;
  options?: CaorenModOption[];
};

export type CaorenModModule = {
  id: string;
  name: string;
  title: string;
  label: string;
  command: string;
  aliases: string[];
  category: string;
  description: string;
  warning?: string;
  params: CaorenModParam[];
  args: CaorenModParam[];
  examples: string[];
  buildCommand: (values?: Record<string, unknown>) => string;
};

export type CaorenModCommandPayload = {
  moduleId?: string;
  id?: string;
  module?: string;
  values?: Record<string, unknown>;
  params?: Record<string, unknown>;
  args?: Record<string, unknown>;
};

export type CaorenModCommandResult = {
  ok: boolean;
  success: boolean;
  error?: string;
  command?: string;
  serverCommand?: string;
  module?: CaorenModModule;
  moduleId?: string;
  values?: Record<string, unknown>;
  label?: string;
  moduleTitle?: string;
  action?: string;
};

const TEAM_OPTIONS: CaorenModOption[] = [
  { label: 'T 阵营', value: 't' },
  { label: 'CT 阵营', value: 'ct' },
  { label: '全体玩家', value: 'all' },
  { label: '禁用模块', value: '0' },
];

const TEAM_OPTIONS_WITH_VIP: CaorenModOption[] = [
  { label: 'T 阵营', value: 't' },
  { label: 'CT 阵营', value: 'ct' },
  { label: '全体玩家', value: 'all' },
  { label: 'VIP 玩家', value: 'vip' },
  { label: '禁用模块', value: '0' },
];

const ESP_MODE_OPTIONS: CaorenModOption[] = [
  { label: '持续透视', value: 0 },
  { label: '准星指着透', value: 1 },
];

function s(values: Record<string, unknown> | undefined, key: string, fallback = ''): string {
  const raw = values?.[key];
  if (raw === undefined || raw === null || raw === '') return fallback;
  return String(raw).trim();
}

function n(values: Record<string, unknown> | undefined, key: string, fallback: number): number {
  const raw = values?.[key];
  if (raw === undefined || raw === null || raw === '') return fallback;
  const parsed = Number(raw);
  return Number.isFinite(parsed) ? parsed : fallback;
}

function b01(values: Record<string, unknown> | undefined, key: string, fallback: boolean): string {
  const raw = values?.[key];
  if (raw === undefined || raw === null || raw === '') return fallback ? '1' : '0';
  if (typeof raw === 'boolean') return raw ? '1' : '0';
  const text = String(raw).trim().toLowerCase();
  return text === '1' || text === 'true' || text === 'yes' || text === 'on' || text === '启用' ? '1' : '0';
}

function btf(values: Record<string, unknown> | undefined, key: string, fallback: boolean): string {
  const raw = values?.[key];
  if (raw === undefined || raw === null || raw === '') return fallback ? 'true' : 'false';
  if (typeof raw === 'boolean') return raw ? 'true' : 'false';
  const text = String(raw).trim().toLowerCase();
  return text === '1' || text === 'true' || text === 'yes' || text === 'on' || text === '启用' ? 'true' : 'false';
}

function target(values: Record<string, unknown> | undefined, fallback = 'all'): string {
  return s(values, 'target', fallback).toLowerCase();
}

function isOffTarget(value: string): boolean {
  const key = value.trim().toLowerCase();
  return key === '0' || key === 'off' || key === 'disable' || key === 'disabled' || key === '禁用';
}

function cmd(parts: Array<string | number | boolean>): string {
  return parts.map((part) => String(part).trim()).filter(Boolean).join(' ');
}

function pTeam(label = '目标', options: CaorenModOption[] = TEAM_OPTIONS): CaorenModParam {
  return { key: 'target', label, type: 'select', options, defaultValue: 'all', default: 'all', required: true };
}

function pNum(key: string, label: string, defaultValue: number, min?: number, max?: number, step = 1, helperText?: string): CaorenModParam {
  return { key, label, type: 'number', defaultValue, default: defaultValue, min, max, step, required: true, helperText };
}

function pText(key: string, label: string, defaultValue: string, helperText?: string): CaorenModParam {
  return { key, label, type: 'text', defaultValue, default: defaultValue, required: true, helperText };
}

function pBool(key: string, label: string, defaultValue: boolean, helperText?: string): CaorenModParam {
  return { key, label, type: 'boolean', defaultValue, default: defaultValue, required: false, helperText };
}

function makeModule(module: Omit<CaorenModModule, 'name' | 'label' | 'args'> & Partial<Pick<CaorenModModule, 'name' | 'label' | 'args'>>): CaorenModModule {
  return {
    ...module,
    name: module.name ?? module.id.toUpperCase(),
    label: module.label ?? module.title,
    args: module.args ?? module.params,
  };
}

export const CAOREN_MOD_MODULES: CaorenModModule[] = [
  makeModule({
    id: 'ammo', name: 'AMMO', title: '弹药与道具不消耗概率', command: 'css_ammo', aliases: ['ammo', 'ammunition', 'grenade'], category: '基础修改',
    description: '控制弹药、投掷物等资源的不消耗概率。命令：css_ammo <t/ct/all/0> [枪械概率] [道具概率]。',
    params: [pTeam(), pNum('bulletChance', '开枪不耗弹 %', 100, 0, 100, 1), pNum('grenadeChance', '道具不消耗 %', 100, 0, 100, 1)],
    examples: ['css_ammo all 50 20', 'css_ammo 0'],
    buildCommand: (v) => { const t = target(v); return isOffTarget(t) ? 'css_ammo 0' : cmd(['css_ammo', t, n(v, 'bulletChance', 100), n(v, 'grenadeChance', 100)]); },
  }),
  makeModule({
    id: 'armor', name: 'ARMOR', title: '防弹衣耐久', command: 'css_armor', aliases: ['armor'], category: '基础修改',
    description: '控制指定阵营购买防弹衣后的护甲耐久。命令：css_armor <t/ct/all/0> <Value>。',
    params: [pTeam(), pNum('value', '护甲参数', 100, 0, 500, 1)],
    examples: ['css_armor all 150', 'css_armor 0'],
    buildCommand: (v) => { const t = target(v); return isOffTarget(t) ? 'css_armor 0' : cmd(['css_armor', t, n(v, 'value', 100)]); },
  }),
  makeModule({
    id: 'aura', name: 'AURA', title: '剑气', command: 'css_aura', aliases: ['aura', 'BladeAura'], category: '基础修改',
    description: '剑气/近战扩展效果。命令：css_aura <t/ct/all/0> [击退联动1/0] [衰减倍率] [最低生效伤害]。',
    params: [pTeam(), pBool('allowKb', '击退联动', true), pNum('decay', '衰减倍率', 0.5, 0, 10, 0.1), pNum('minDamage', '最低生效伤害', 15, 0, 500, 1)],
    examples: ['css_aura all 1 0.5 15', 'css_aura 0'],
    buildCommand: (v) => { const t = target(v); return isOffTarget(t) ? 'css_aura 0' : cmd(['css_aura', t, b01(v, 'allowKb', true), n(v, 'decay', 0.5), n(v, 'minDamage', 15)]); },
  }),
  makeModule({
    id: 'cash', name: 'CASH', title: '经济倍率', command: 'css_cash', aliases: ['cash', 'money', 'Money'], category: '基础修改',
    description: '经济奖励/倍率控制。命令：css_cash <t/ct/all/0> <倍数> [1/0回合奖励]。',
    params: [pTeam(), pNum('multiplier', '经济倍率', 1, 0, 20, 0.1), pBool('roundReward', '影响回合奖励', true)],
    examples: ['css_cash all 2 1', 'css_cash ct 1.5 0', 'css_cash 0'],
    buildCommand: (v) => { const t = target(v); return isOffTarget(t) ? 'css_cash 0' : cmd(['css_cash', t, n(v, 'multiplier', 1), b01(v, 'roundReward', true)]); },
  }),
  makeModule({
    id: 'fov', name: 'FOV', title: 'FOV', command: 'css_fov', aliases: ['fov', 'fieldofview'], category: '基础修改',
    description: '视野 FOV 调整。命令：css_fov <t/ct/all/0> <30-150>。',
    params: [pTeam(), pNum('value', 'FOV 数值', 110, 30, 150, 1)],
    examples: ['css_fov all 110', 'css_fov 0'],
    buildCommand: (v) => { const t = target(v); return isOffTarget(t) ? 'css_fov 0' : cmd(['css_fov', t, n(v, 'value', 110)]); },
  }),
  makeModule({
    id: 'doublejump', name: 'DJ / DoubleJump', title: '二段跳/多段跳', command: 'css_dj', aliases: ['dj', 'doublejump', 'DoubleJump'], category: '基础修改',
    description: '二段跳/多段跳控制。命令：css_dj <t/ct/all/0> <跳跃次数> <高度力度> <上升期起跳true/false>。',
    params: [pTeam(), pNum('jumps', '额外跳跃次数', 2, 1, 10, 1), pNum('velocity', '高度力度', 300, 0, 2000, 10), pBool('allowInstantJump', '上升期也能起跳', true, 'true=空中上升阶段也能继续跳；false=必须下落阶段才能连跳。')],
    examples: ['css_dj t 2 300 true', 'css_dj all 3 250 false', 'css_dj 0'],
    buildCommand: (v) => { const t = target(v); return isOffTarget(t) ? 'css_dj 0' : cmd(['css_dj', t, n(v, 'jumps', 2), n(v, 'velocity', 300), btf(v, 'allowInstantJump', true)]); },
  }),
  makeModule({
    id: 'hpcap', name: 'HPCAP', title: '血量上下限', command: 'css_hpcap', aliases: ['hpcap', 'healthcap', 'hp'], category: '生命修改',
    description: '全局模块血量上下限，供流血、回血、击杀回血、友伤等模块共用。命令：css_hpcap <最低血量> <最高血量>。',
    params: [pNum('min', '最低血量', 1, 0, 1000, 1), pNum('max', '最高血量', 100, 1, 5000, 1)],
    examples: ['css_hpcap 1 100', 'css_hpcap 1 200'],
    buildCommand: (v) => cmd(['css_hpcap', n(v, 'min', 1), n(v, 'max', 100)]),
  }),
  makeModule({
    id: 'dmg', name: 'DMG / Damage', title: '伤害倍率/锁血上限', command: 'css_dmg', aliases: ['dmg', 'damage', 'DamageScaler'], category: '生命修改',
    description: '指定阵营受伤倍率和时间窗口伤害上限。命令：css_dmg <t/ct/all/0> <倍率/-> <上限Cap> <时间窗口秒>。',
    params: [pTeam(), pText('multiplier', '易伤倍率 / -', '1', '填 1 为原版；填 2 为双倍；填 - 保留当前倍率只改锁血。'), pNum('cap', '窗口伤害上限', 100, 0, 10000, 1), pNum('window', '窗口秒数', 5, 0, 120, 1)],
    examples: ['css_dmg t 2 50 1.5', 'css_dmg all - 100 5', 'css_dmg 0'],
    buildCommand: (v) => { const t = target(v); return isOffTarget(t) ? 'css_dmg 0' : cmd(['css_dmg', t, s(v, 'multiplier', '1'), n(v, 'cap', 100), n(v, 'window', 5)]); },
  }),
  makeModule({
    id: 'incdmg', name: 'INCDMG / DynamicDamage', title: '动态时间伤害', command: 'css_incdmg', aliases: ['incdmg', 'dynamicdamage', 'timeDamage'], category: '生命修改',
    description: '随时间增伤/减伤。命令：css_incdmg <t/ct/all/0> [倍率]。',
    params: [pTeam(), pNum('rate', '每 5 秒倍率变化', 0.01, -10, 10, 0.01)],
    examples: ['css_incdmg all 0.01', 'css_incdmg ct -0.01', 'css_incdmg 0'],
    buildCommand: (v) => { const t = target(v); return isOffTarget(t) ? 'css_incdmg 0' : cmd(['css_incdmg', t, n(v, 'rate', 0.01)]); },
  }),
  makeModule({
    id: 'bleed', name: 'BLEED / BleedRegen', title: '持续流血/回血', command: 'css_bleed', aliases: ['bleed', 'regen', 'blood'], category: '生命修改',
    description: '固定间隔扣血或回血；血量上下限由 css_hpcap 控制。命令：css_bleed <t/ct/all/0> <秒> <数值>。',
    params: [pTeam(), pNum('interval', '间隔秒数', 1, 0.1, 120, 0.1), pNum('amount', '血量变化', -5, -1000, 1000, 1)],
    examples: ['css_bleed t 1 -5', 'css_bleed all 2 3', 'css_bleed 0'],
    buildCommand: (v) => { const t = target(v); return isOffTarget(t) ? 'css_bleed 0' : cmd(['css_bleed', t, n(v, 'interval', 1), n(v, 'amount', -5)]); },
  }),
  makeModule({
    id: 'kh', name: 'KH / KillHeal', title: '击杀回血/击杀扣血', command: 'css_kh', aliases: ['kh', 'killheal', 'KillHeal', '击杀'], category: '生命修改',
    description: '击杀后恢复或扣除击杀者血量；支持 T、CT、全员、VIP。血量上下限由 css_hpcap 控制。命令：css_kh <t/ct/all/vip/0> [变动数值]。',
    params: [pTeam('目标', TEAM_OPTIONS_WITH_VIP), pNum('amount', '击杀后血量变化', 25, -1000, 1000, 1)],
    examples: ['css_kh t 50', 'css_kh vip -10', 'css_kh 0'],
    buildCommand: (v) => { const t = target(v); return isOffTarget(t) ? 'css_kh 0' : cmd(['css_kh', t, n(v, 'amount', 25)]); },
  }),
  makeModule({
    id: 'kb', name: 'KB / KnockBack', title: '动能击退', command: 'css_kb', aliases: ['kb', 'knockback', 'KnockBack'], category: '物理修改',
    description: '伤害触发物理击退。命令：css_kb <t/ct/all/0> [水平力] [垂直力] [友军生效1/0] [伤害倍数]。',
    params: [pTeam('发起方'), pNum('horizontal', '水平力', 400, 0, 5000, 10), pNum('vertical', '垂直力', 250, 0, 5000, 10), pBool('friendly', '友军/自伤也生效', true), pNum('damageMultiplier', '伤害系数', 2, 0, 100, 0.1)],
    examples: ['css_kb all 400 250 1 2.0', 'css_kb ct 300 180 0 1', 'css_kb 0'],
    buildCommand: (v) => { const t = target(v); return isOffTarget(t) ? 'css_kb 0' : cmd(['css_kb', t, n(v, 'horizontal', 400), n(v, 'vertical', 250), b01(v, 'friendly', true), n(v, 'damageMultiplier', 2)]); },
  }),
  makeModule({
    id: 'lhimm', name: 'LHIMM / LastHitImmune', title: '名刀无敌', command: 'css_lhimm', aliases: ['lhimm', 'lastHitImmune', 'last-hit-immune'], category: '生命修改',
    description: '玩家每条命第一次受到致命伤害时保留 1 HP，并获得短暂无敌与速度加成。命令：css_lhimm <t/ct/all/0> <Time> <extraSpeed>。',
    params: [pTeam(), pNum('time', '无敌时间秒', 3, 0, 120, 0.1), pNum('extraSpeed', '额外速度百分比', 50, 0, 1000, 1)],
    examples: ['css_lhimm t 3 50', 'css_lhimm all 2.5 30', 'css_lhimm 0'],
    buildCommand: (v) => { const t = target(v); return isOffTarget(t) ? 'css_lhimm 0' : cmd(['css_lhimm', t, n(v, 'time', 3), n(v, 'extraSpeed', 50)]); },
  }),
  makeModule({
    id: 'smoke', name: 'SMOKE', title: '烟雾弹：毒烟/奶烟/持续时间', command: 'css_smoke', aliases: ['smoke', 'smokegrenade'], category: '投掷物修改',
    description: '控制指定阵营烟雾弹存在时长，以及玩家在烟内每秒扣血或回血。命令：css_smoke <t/ct/all/0> <持续时间/-> <正回血负扣血>。',
    params: [pTeam('烟雾所属阵营/受影响目标'), pText('duration', '烟雾持续时间', '-', '填 - 表示保持默认时长；填 10 表示强制 10 秒。'), pNum('hpChange', '每秒血量变化', -5, -1000, 1000, 1)],
    examples: ['css_smoke t - -5', 'css_smoke all 10 3', 'css_smoke 0'],
    buildCommand: (v) => { const t = target(v); return isOffTarget(t) ? 'css_smoke 0' : cmd(['css_smoke', t, s(v, 'duration', '-'), n(v, 'hpChange', -5)]); },
  }),
  makeModule({
    id: 'esp', name: 'ESP', title: 'ESP 透视发光', command: 'css_esp', aliases: ['esp', 'wallhack', 'glow'], category: '视野修改',
    description: '指定阵营可透过墙壁看到敌方发光模型。命令：css_esp <t/ct/all/0> [最远距离] [模式]。',
    params: [pTeam('透视者阵营'), pNum('range', '最近距离', 5000, 0, 50000, 100), { key: 'mode', label: '模式', type: 'select', options: ESP_MODE_OPTIONS, defaultValue: 0, default: 0, required: true }],
    examples: ['css_esp all 5000 0', 'css_esp ct 3000 1', 'css_esp 0'],
    buildCommand: (v) => { const t = target(v); return isOffTarget(t) ? 'css_esp 0' : cmd(['css_esp', t, n(v, 'range', 5000), n(v, 'mode', 0)]); },
  }),
  makeModule({
    id: 'ffire', name: 'FFIRE / FriendlyFire', title: '友伤倍率/友伤回血', command: 'css_ffire', aliases: ['ffire', 'friendlyfire', 'FriendlyFire'], category: '伤害修改',
    description: '深度控制友军伤害：正数扣血，0 免疫，负数把友伤变回血。命令：css_ffire <t/ct/all/0> <倍率> <1/0是否允许击杀>。',
    params: [pTeam('攻击者阵营'), pNum('multiplier', '友伤倍率', 1, -100, 100, 0.1), pBool('allowKill', '允许友伤击杀', false)],
    examples: ['css_ffire all 1 0', 'css_ffire ct -1 0', 'css_ffire 0'],
    buildCommand: (v) => { const t = target(v); return isOffTarget(t) ? 'css_ffire 0' : cmd(['css_ffire', t, n(v, 'multiplier', 1), b01(v, 'allowKill', false)]); },
  }),
  makeModule({
    id: 'fh', name: 'FH / FireHeal', title: '火疗/火焰伤害', command: 'css_fh', aliases: ['fh', 'fireheal', 'FireHeal'], category: '投掷物修改',
    description: '控制火焰伤害倍率。0 免疫，负数把火伤转为回血，正数为伤害倍率。命令：css_fh <t/ct/all/0> <倍率>。',
    params: [pTeam(), pNum('scale', '火焰倍率', -1, -100, 100, 0.1)],
    examples: ['css_fh all 0', 'css_fh t -1', 'css_fh 0'],
    buildCommand: (v) => { const t = target(v); return isOffTarget(t) ? 'css_fh 0' : cmd(['css_fh', t, n(v, 'scale', -1)]); },
  }),
  makeModule({
    id: 'wspd', name: 'WSPD / WeaponSpeed', title: '武器切枪/射击速度', command: 'css_wspd', aliases: ['wspd', 'weaponspeed', 'WeaponSpeed'], category: '武器修改',
    description: '控制指定阵营武器切枪速度与射击速度百分比。100 为原速，200 为两倍。命令：css_wspd <t/ct/all/0> <switchSpeed> <fireSpeed>。',
    params: [pTeam(), pNum('switchSpeed', '切枪速度 %', 100, 0, 1000, 1), pNum('fireSpeed', '射击速度 %', 200, 0, 1000, 1)],
    examples: ['css_wspd all 100 200', 'css_wspd ct 80 150', 'css_wspd 0'],
    buildCommand: (v) => { const t = target(v); return isOffTarget(t) ? 'css_wspd 0' : cmd(['css_wspd', t, n(v, 'switchSpeed', 100), n(v, 'fireSpeed', 200)]); },
  }),
  makeModule({
    id: 'tag', name: 'TAG / Tagging', title: '受击速度控制', command: 'css_tag', aliases: ['tag', 'tagging', 'TaggingControl'], category: '移动修改',
    description: '控制玩家被击中后的减速倍率。df/default 恢复官方默认。命令：css_tag <目标/0> <倍率/df>。',
    params: [pTeam(), pText('value', '速度倍率 / df', '1.0', '填 df/default 恢复默认；0 表示无减速；1.0 表示原版减速。')],
    examples: ['css_tag t 1.0', 'css_tag ct df', 'css_tag 0'],
    buildCommand: (v) => { const t = target(v); return isOffTarget(t) ? 'css_tag 0' : cmd(['css_tag', t, s(v, 'value', '1.0')]); },
  }),
  makeModule({
    id: 'magic', name: 'MAGIC / MagicBullet', title: '魔法弹道吸附', command: 'css_magic', aliases: ['magic', 'magicbullet', 'Magic'], category: '武器修改',
    description: '子弹打到墙面或地面时，在指定半径内回溯吸附敌人并造成额外伤害。命令：css_magic <t/ct/all/0> [吸附半径] [单次伤害]。',
    params: [pTeam('拥有魔法弹道的阵营'), pNum('radius', '吸附半径', 60, 0, 5000, 1), pNum('damage', '单次伤害', 20, 0, 1000, 1)],
    examples: ['css_magic all 60 20', 'css_magic t 120 15', 'css_magic 0'],
    buildCommand: (v) => { const t = target(v); return isOffTarget(t) ? 'css_magic 0' : cmd(['css_magic', t, n(v, 'radius', 60), n(v, 'damage', 20)]); },
  }),
  makeModule({
    id: 'bq', name: 'BQ / BombQuiz', title: '黑客攻防/拆包答题', command: 'css_bq', aliases: ['bq', 'bombquiz', 'BombQuiz'], category: '玩法修改',
    description: '下包后触发算术题攻防。题型组合可填 147 表示在 1、4、7 中随机抽取。命令：css_bq <题型组合/0> [强制秒数/0] [CT延迟秒数]。',
    params: [pText('quizTypes', '题型组合 / 0禁用', '147', '例如 147 表示从题型 1、4、7 中随机抽取；填 0 禁用。'), pNum('overrideTime', '强制秒数 / 0自动', 0, 0, 300, 1), pText('ctDelay', 'CT 延迟秒数', 'auto', '填 auto 表示动态公式；填 2 表示强制延迟 2 秒。')],
    examples: ['css_bq 147', 'css_bq 147 10 2', 'css_bq 0'],
    buildCommand: (v) => { const quizTypes = s(v, 'quizTypes', '147').replace(/[^0-7]/g, '') || '1'; if (quizTypes === '0') return 'css_bq 0'; const over = n(v, 'overrideTime', 0); const ctRaw = s(v, 'ctDelay', 'auto').toLowerCase(); if (ctRaw === 'auto' || ctRaw === '动态' || ctRaw === 'default' || ctRaw === '') return cmd(['css_bq', quizTypes, over]); return cmd(['css_bq', quizTypes, over, ctRaw]); },
  }),
  makeModule({
    id: 'reset_all', name: 'RESET', title: '重置所有 CaorenCup 修改', command: 'reset_plu', aliases: ['reset', 'reset_plu'], category: '重置',
    description: '调用娱乐插件本体的重置命令，恢复当前一组修改。', warning: '会影响多个娱乐模块，请确认当前对局允许重置。',
    params: [], examples: ['reset_plu'], buildCommand: () => 'reset_plu',
  }),
];

export const caorenModModules = CAOREN_MOD_MODULES;
export const caorenModules = CAOREN_MOD_MODULES;
export const CAOREN_MODULES = CAOREN_MOD_MODULES;

export const ALLOWED_CAOREN_SERVER_COMMANDS = Array.from(new Set(
  CAOREN_MOD_MODULES.map((module) => module.command).concat(['reset_plu'])
)).sort();

export function getCaorenModules(): CaorenModModule[] { return CAOREN_MOD_MODULES; }
export function getCaorenModModules(): CaorenModModule[] { return CAOREN_MOD_MODULES; }
export function listCaorenModules(): CaorenModModule[] { return CAOREN_MOD_MODULES; }
export function getPublicCaorenModules(): CaorenModModule[] { return CAOREN_MOD_MODULES; }

export function findCaorenModule(moduleId: string | undefined | null): CaorenModModule | undefined {
  if (!moduleId) return undefined;
  const key = moduleId.trim().toLowerCase();
  return CAOREN_MOD_MODULES.find((module) => {
    if (module.id.toLowerCase() === key) return true;
    if (module.command.toLowerCase() === key) return true;
    if (module.aliases.some((alias) => alias.toLowerCase() === key)) return true;
    if (module.aliases.some((alias) => ('css_' + alias.toLowerCase()) === key)) return true;
    return false;
  });
}

export function buildCaorenModCommand(moduleIdOrPayload: string | CaorenModCommandPayload, valuesArg?: Record<string, unknown>): string {
  const moduleId = typeof moduleIdOrPayload === 'string' ? moduleIdOrPayload : moduleIdOrPayload.moduleId ?? moduleIdOrPayload.id ?? moduleIdOrPayload.module;
  const values = typeof moduleIdOrPayload === 'string' ? (valuesArg ?? {}) : (moduleIdOrPayload.values ?? moduleIdOrPayload.params ?? moduleIdOrPayload.args ?? {});
  const module = findCaorenModule(moduleId);
  if (!module) throw new Error('未知 CaorenCup 修改模块：' + (moduleId ?? '(empty)'));
  return module.buildCommand(values);
}

export const buildCaorenCommand = buildCaorenModCommand;
export const buildServerCommand = buildCaorenModCommand;
export const buildCaorenModServerCommand = buildCaorenModCommand;

export function validateCaorenModCommand(moduleIdOrPayload: string | CaorenModCommandPayload, valuesArg?: Record<string, unknown>): CaorenModCommandResult {
  try {
    const moduleId = typeof moduleIdOrPayload === 'string' ? moduleIdOrPayload : moduleIdOrPayload.moduleId ?? moduleIdOrPayload.id ?? moduleIdOrPayload.module;
    const values = typeof moduleIdOrPayload === 'string' ? (valuesArg ?? {}) : (moduleIdOrPayload.values ?? moduleIdOrPayload.params ?? moduleIdOrPayload.args ?? {});
    const module = findCaorenModule(moduleId);
    if (!module) return { ok: false, success: false, error: '未知 CaorenCup 修改模块：' + (moduleId ?? '(empty)') };
    const command = module.buildCommand(values);
    const firstToken = command.split(/\s+/)[0]?.toLowerCase();
    const allowed = ALLOWED_CAOREN_SERVER_COMMANDS.map((item) => item.toLowerCase());
    if (!firstToken || !allowed.includes(firstToken)) return { ok: false, success: false, error: '命令不在网页端白名单内：' + (firstToken ?? '(empty)') };
    return { ok: true, success: true, command, serverCommand: command, module, moduleId: module.id, values, label: module.label ?? module.title, moduleTitle: module.title ?? module.label, action: command };
  } catch (error) {
    return { ok: false, success: false, error: error instanceof Error ? error.message : String(error) };
  }
}

export const validateCaorenCommand = validateCaorenModCommand;
export const validateCaorenModCommandPayload = validateCaorenModCommand;
export const validateCaorenModRequest = validateCaorenModCommand;

export default CAOREN_MOD_MODULES;

export const getCaorenModuleDefinitions = getPublicCaorenModules;
export const buildCaorenCommandFromRequest = validateCaorenModCommand;
